[pytest]
addopts = -s -v
asyncio_mode = auto
python_files = *_tests.py test_*.py
python_classes = Test*
python_functions = test_*
markers =
    template: Базовые шаблонные тесты проекта.
    integration: Интеграционные тесты к реальному API.
