from __future__ import annotations

from schema.rbac import AccessRule


ACCESS_POLICY_USER: list[AccessRule] = [
    AccessRule(
        name="User: get existing user by username",
        method="POST",
        path="/api/user/get",
        allowed_roles=["admin", "user"],
        denied_roles=["super_admin"],
        expected_allowed_status=200,
        expected_denied_status=403,
        json_body={"user_name": "$USER_NAME"},
    ),
    AccessRule(
        name="User: get non-existing user by username",
        method="POST",
        path="/api/user/get",
        allowed_roles=["admin", "user"],
        denied_roles=["super_admin"],
        expected_allowed_status=404,
        expected_denied_status=403,
        json_body={"user_name": "user_that_does_not_exist_qa_12345"},
    ),
    AccessRule(
        name="User: get existing user by id",
        method="POST",
        path="/api/user/get_by_id",
        allowed_roles=["admin", "user"],
        denied_roles=["super_admin"],
        expected_allowed_status=200,
        expected_denied_status=403,
        json_body={"user_id": "$USER_ID"},
    ),
    AccessRule(
        name="User: get non-existing user by id",
        method="POST",
        path="/api/user/get_by_id",
        allowed_roles=["admin", "user"],
        denied_roles=["super_admin"],
        expected_allowed_status=404,
        expected_denied_status=403,
        json_body={"user_id": "000000000000000000000000"},
    ),
    AccessRule(
        name="User: get all users",
        method="POST",
        path="/api/user/get_all",
        allowed_roles=["admin", "super_admin"],
        denied_roles=["user"],
        expected_allowed_status=200,
        expected_denied_status=403,
        json_body={},
    ),
    AccessRule(
        name="User: get system roles",
        method="POST",
        path="/api/user/get_roles",
        allowed_roles=["admin", "user"],
        denied_roles=["super_admin"],
        expected_allowed_status=200,
        expected_denied_status=403,
        json_body={},
    ),
    AccessRule(
        name="User: update non-existing user",
        method="POST",
        path="/api/user/update",
        allowed_roles=["admin", "user"],
        denied_roles=["super_admin"],
        expected_allowed_status=404,
        expected_denied_status=403,
        data={"user_id": "000000000000000000000000", "first_name": "RBAC"},
    ),
    AccessRule(
        name="User: create with invalid email",
        method="POST",
        path="/api/user/create",
        allowed_roles=["admin", "super_admin"],
        denied_roles=["user"],
        expected_allowed_status=422,
        expected_denied_status=403,
        data={
            "org_name": "$ORG_NAME",
            "user_name": "rbac-create-check",
            "first_name": "RBAC",
            "last_name": "Check",
            "role_id": "$USER_ROLE_ID",
            "email": "invalid-email",
        },
    ),
    AccessRule(
        name="User: delete non-existing user",
        method="POST",
        path="/api/user/delete",
        allowed_roles=["admin", "super_admin"],
        denied_roles=["user"],
        expected_allowed_status=404,
        expected_denied_status=403,
        json_body={"user_id": "000000000000000000000000"},
    ),
    AccessRule(
        name="User: unlock non-existing user",
        method="POST",
        path="/api/user/unlock_user",
        allowed_roles=["admin", "super_admin"],
        denied_roles=["user"],
        expected_allowed_status=404,
        expected_denied_status=403,
        json_body={"username": "nonexistent_user_qa_12345"},
    ),
    AccessRule(
        name="User: reset MFA for non-existing user",
        method="POST",
        path="/api/user/reset_user_mfa",
        allowed_roles=["admin", "super_admin"],
        denied_roles=["user"],
        expected_allowed_status=404,
        expected_denied_status=403,
        json_body={"user_id": "000000000000000000000000"},
    ),
]
